### ISSUE TITLE
 Vaadin 14 Apex chart and grid css FlexibleGridLayout

### ISSUE THREAD

**Issue by rucko24** [appreciated/appreciated-collection#2]
Hi, apex chart and grid css FlexibleGridLayout, when will they be compatible with vaadin 14?

> java.lang.IllegalArgumentException: Unable to create an instance of 'com.github.appreciated.layout.GridLayout'. The constructor threw an exception.

> java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'apex-charts-wrapper' in any template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file

thanks a lot...

**Comment by appreciated** [comment]
Hi @rucko24! Both addons already are compatible with Vaadin 14 + Npm. Before starting you seem to have forgotten to run a prepare-frontend goal
